# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizableProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Permission')),
                ('project_key', models.CharField(max_length=100, verbose_name='Permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('request_granted', models.BooleanField()),
                ('date_request_granted', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.AuthorizableProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.AuthorizableProject'),
        ),
    ]
