# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20161224_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizableproject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='authorizableproject',
            name='project_key',
            field=models.CharField(max_length=100, verbose_name='project_key'),
        ),
        migrations.AlterField(
            model_name='userpermissionrequest',
            name='date_request_granted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpermissionrequest',
            name='request_granted',
            field=models.BooleanField(default=False),
        ),
    ]
