# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0003_auto_20161227_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUseAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('agreement_text', models.CharField(max_length=1000, verbose_name='Agreement Text')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.AuthorizableProject')),
            ],
        ),
        migrations.CreateModel(
            name='DataUseAgreementSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('data_use_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.DataUseAgreement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
