# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_datauseagreement_datauseagreementsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauseagreement',
            name='agreement_text',
            field=models.TextField(),
        ),
    ]
