# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20161227_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizableproject',
            name='dua_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='authorizableproject',
            name='permission_scheme',
            field=models.CharField(default='PRIVATE', max_length=100, verbose_name='Permission Scheme'),
        ),
        migrations.AlterField(
            model_name='authorizableproject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='authorizableproject',
            name='project_key',
            field=models.CharField(max_length=100, verbose_name='Project Key'),
        ),
    ]
