# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-02 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20161229_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauseagreement',
            name='agreement_form',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='datauseagreement',
            name='agreement_text',
            field=models.TextField(null=True),
        ),
    ]
