# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_auto_20171102_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauseagreementsign',
            name='agreement_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
