# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-03 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_datauseagreementsign_agreement_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauseagreement',
            old_name='agreement_form',
            new_name='agreement_form_file',
        ),
    ]
