# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_auto_20171103_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauseagreement',
            name='agreement_form_file',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
