# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_auto_20171103_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauseagreement',
            name='agreement_form_file',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datauseagreement',
            name='agreement_text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
