# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-13 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0012_auto_20171103_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizableproject',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
