# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-14 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_authorizableproject_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizableproject',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='project_manager',
            field=models.BooleanField(default=False),
        ),
    ]
