# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-14 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_authorizableproject_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizableproject',
            name='project_manager',
        ),
    ]
