# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-14 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_remove_authorizableproject_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauseagreement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='datauseagreementsign',
            name='data_use_agreement',
        ),
        migrations.RemoveField(
            model_name='datauseagreementsign',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userpermissionrequest',
            name='project',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='item',
            field=models.CharField(default='', max_length=100, verbose_name=b'Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpermissionrequest',
            name='item',
            field=models.CharField(default='', max_length=100, verbose_name=b'Item'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AuthorizableProject',
        ),
        migrations.DeleteModel(
            name='DataUseAgreement',
        ),
        migrations.DeleteModel(
            name='DataUseAgreementSign',
        ),
    ]
