# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_auto_20171214_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='item',
            field=models.CharField(max_length=100, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='userpermissionrequest',
            name='date_request_granted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpermissionrequest',
            name='item',
            field=models.CharField(max_length=100, verbose_name='Item'),
        ),
    ]
