# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0018_auto_20180228_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='user_email',
            field=models.CharField(default='', max_length=250, verbose_name='User Email'),
            preserve_default=False,
        ),
    ]
