# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-23 17:11
from __future__ import unicode_literals

from django.db import migrations, models

def migrate_user_field(apps, schema_editor):
    """
    Take the User field and copy the email addresses into the User_Email field.
    """

    UserPermission = apps.get_model("authorization", "userpermission")

    # All data available is small enough that looping over them won't take long
    for permission in UserPermission.objects.all():
        permission.user_email = permission.user.email
        permission.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0019_userpermission_user_email'),
    ]

    operations = [
        migrations.RunPython(migrate_user_field),
    ]
