# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-24 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0020_auto_20180823_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
    ]
